export const enum configServiceKeys {
  APP_NAME = 'APP_NAME',
  NODE_ENV = 'NODE_ENV',

  BACKEND_PORT = 'BACKEND_PORT',
  BACKEND_LINK = 'BACKEND_LINK',
  FRONTEND_LINK = 'FRONTEND_LINK',

  MONGODB_PORT = 'MONGODB_PORT',
  MONGODB_DATABASE = 'MONGODB_DATABASE',
  MONGODB_HOSTNAME = 'MONGODB_HOSTNAME',
  MONGODB_USERNAME = 'MONGODB_USERNAME',
  MONGODB_PASSWORD = 'MONGODB_PASSWORD',
  MONGODB_AUTH_SOURCE = 'MONGODB_AUTH_SOURCE',

  API_KEY = 'API_KEY'
}
